"""add memories tables

Revision ID: 6225189a493b
Revises: 1c81df873f21
Create Date: 2025-09-08 00:31:20.429527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6225189a493b'
down_revision: Union[str, Sequence[str], None] = '1c81df873f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_title'), 'memories', ['title'], unique=True)
    op.create_table('memory_relations',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['memories.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['memories.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memory_relations')
    op.drop_index(op.f('ix_memories_title'), table_name='memories')
    op.drop_table('memories')
    # ### end Alembic commands ###
