"""update memories

Revision ID: f2a19b009b45
Revises: 6225189a493b
Create Date: 2025-09-13 23:35:29.916077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2a19b009b45'
down_revision: Union[str, Sequence[str], None] = '6225189a493b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('source_url', sa.String(length=500), nullable=True))
    op.add_column('memories', sa.Column('memory_simplicity', sa.Integer(), server_default='0', nullable=False))
    op.add_column('memories', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_memories_memory_simplicity', 'memories', ['memory_simplicity'], unique=False)
    op.add_column('memory_relations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('memory_relations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memory_relations', 'updated_at')
    op.drop_column('memory_relations', 'created_at')
    op.drop_index('ix_memories_memory_simplicity', table_name='memories')
    op.drop_column('memories', 'updated_at')
    op.drop_column('memories', 'memory_simplicity')
    op.drop_column('memories', 'source_url')
    # ### end Alembic commands ###
